server:
  port: 8090

spring:
#  main:
#    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://192.168.1.23:5432/ai-rag-cactusli
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1
  ai:
    mcp:
      client:
#        stdio:
#          servers-configuration: classpath:/config/mcp-servers-config-3.json
        sse:
          connections:
            mcp-server-csdn:
              url: http://192.168.1.23:8101
            mcp-server-weixin:
              url: http://192.168.1.23:8102
        request-timeout: 521s

    openai:
      base-url: https://chat.199228.xyz/
      api-key: your_openai_api_key_here
      chat:
        options:
          model: gpt-4o
      embedding-model: text-embedding-3-small
      embedding:
        options:
          num-batch: 1536
    ollama:
      base-url: http://58a39caa684c41bf9bed-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768

cron:
  expression: 0 * * * * ?

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
